version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "month"
    commit-message:
      prefix: "deps"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "month"
    commit-message:
      prefix: "ci"
